Repository LadHrAnalytics/ML_HR, pull requests merged in 2024-07, with the labels that each got.

#1 Hh dataset prepocessing
  .gitignore
  Notebooks/dataset_cleaning.ipynb
Labels: enhancement

#2 Habr
  Notebooks/Habr_cleaning.ipynb
Labels: enhancement, help wanted

#5 Hh dataset prepocessing
  .gitignore
  Notebooks/dataset_cleaning.ipynb
  source_data/skills_dictionary.json
Labels: enhancement

#9 New version of Hh cleaning
  .gitignore
  Notebooks/dataset_cleaning.ipynb
Labels: enhancement

#11 Habr
  Notebooks/Analysis_hh.ipynb
  Notebooks/Gradio_Toy.ipynb
  Notebooks/Habr_cleaning.ipynb
  Notebooks/habr_outliers.ipynb
Labels: enhancement

#12 Hh final version
  Notebooks/dataset_cleaning.ipynb
  Notebooks/transformers.py
  source_data/skills_priority.json
Labels: enhancement

#14 Rename dataset_cleaning.ipynb to hh_main_notebook.ipynb
  Notebooks/hh_main_notebook.ipynb
Labels: invalid

#16 Gradio updated
  .gitignore
  Notebooks/Gradio_Toy.ipynb
Labels: enhancement

#17 Delete Notebooks/Gradio_Toy.ipynb
  Notebooks/Gradio_Toy.ipynb
Labels: invalid

#18 Add files via upload
  Notebooks/Gradio_Toy.ipynb
Labels: enhancement
